### ISSUE TITLE
Configuration for generating download notebooks for QuantEcon

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinx-tojupyter#11]
```python
# ----------------
# sphinx-tojupyter
# ----------------

tojupyter_static_file_path = ["source/_static", "_static"]
tojupyter_kernels = {
    "python3": {
        "kernelspec": {
            "display_name": "Python",
            "language": "python3",
            "name": "python3"
            },
        "file_extension": ".py",
    },
}
tojupyter_target_html = True
tojupyter_urlpath = "https://python-programming.quantecon.org/"
tojupyter_image_urlpath = "https://python-programming.quantecon.org/_static/"
tojupyter_lang_synonyms = ["ipython", "ipython3", "python"]
tojupyter_images_markdown = True
tojupyter_allow_html_only=True
```

**Comment by mmcky** [comment]
for `pdf`

```yaml
    tojupyter_kernels:
      python3:
        kernelspec:
          display_name: "Python"
          language: python3
          name: python3
        file_extension: ".py"
    tojupyter_images_markdown: true
    tojupyter_template_path: ../templates/
    tojupyter_latex_template: latex.tpl
    tojupyter_latex_template_book: latex_book.tpl
```
